// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKIa_Tx8BizI5XSDH2tfmU4mnrNL2vgk',
    appId: '1:349964150947:android:d5e55671563f7774ecf716',
    messagingSenderId: '349964150947',
    projectId: 'rapi-5800f',
    storageBucket: 'rapi-5800f.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDnwepcrwt3Q9pEgWNKa8Q7f16qNa29C18",
    authDomain: "rapi-5800f.firebaseapp.com",
    projectId: "rapi-5800f",
    storageBucket: "rapi-5800f.appspot.com",
    messagingSenderId: "349964150947",
    appId: "1:349964150947:web:13849050e1e76e3aecf716"
  );
}
